spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: jdbc:h2:mem:test
    password:
    jdbc-url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug