spring:
  application:
    # core, domain, infrastructure
    name: core
  profiles:
    active: local
  #Label을 사용하고자 하였으나, Directory별 분류를 하고 applicationName별로 분류 했다보니 불필요해짐.
#  cloud:
#    config:
#      label: movie
  config:
    import: optional:configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: "*"